# DigitalOut Message
# This message is used to send desired digital output states to the io-controller

uint8 DIGITAL_OUT_H_01=1
uint8 DIGITAL_OUT_H_02=2
uint8 DIGITAL_OUT_H_03=3
uint8 DIGITAL_OUT_H_04=4
uint8 DIGITAL_OUT_H_05=5
uint8 DIGITAL_OUT_H_06=6
uint8 DIGITAL_OUT_L_01=7
uint8 DIGITAL_OUT_L_02=8
uint8 DIGITAL_OUT_L_03=9
uint8 DIGITAL_OUT_L_04=10
uint8 DIGITAL_OUT_L_05=11
uint8 DIGITAL_OUT_L_06=12

uint8 d_out_pin_id          # Digital output pin id
uint8 duty_cycle_percent    # Duty cycle in percentage (0-100)
