# DigitalOut Message
# This message is used to send desired digital output states to the io-controller

uint8 DIGITAL_OUT_01=1
uint8 DIGITAL_OUT_02=2
uint8 DIGITAL_OUT_03=3
uint8 DIGITAL_OUT_04=4
uint8 DIGITAL_OUT_05=5
uint8 DIGITAL_OUT_06=6
uint8 DIGITAL_OUT_07=7
uint8 DIGITAL_OUT_08=8
uint8 DIGITAL_OUT_09=9
uint8 DIGITAL_OUT_10=10

uint8 d_out_pin_id          # Digital output pin id
uint8 duty_cycle_percent    # Duty cycle in percentage (0-100)
